# Spring Boot
spring:
  application:
    name: "bba-api"
  main:
    banner-mode: "off"
  mvc:
    favicon.enabled: false
  datasource:
    url: "jdbc:mysql://${DB_HOST:localhost}:3306/bba?useLegacyDatetimeCode=false&serverTimezone=US/Mountain"
    username: bba
    password: bba
  jpa:
    open-in-view: false
  jackson:
    default-property-inclusion: "NON_NULL"
    serialization:
      write_dates_as_timestamps: false

---

# VM Options: -Dspring.profiles.active=dev
spring:
  profiles: dev
  datasource:
    url: "jdbc:h2:mem:testdb"
    # driverClassName: "org.h2.Driver"
    username: sa
    password:
    data: classpath:/dev/seed-data.sql
  jpa:
    open-in-view: false
    #    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: "/h2"
logging:
  level:
    root: info
    com.bba: debug
    # org.springframework.security.web.authentication: debug
